First hometask
TimurTechnopolis/advanced_java_course_2018 pull request #47
Opened 2018-10-21 10:24 UTC by AlexPentagon

2018-10-29 05:48 UTC, TimurTechnopolis commented on .idea/libraries/gradle_wrapper.xml
> +<component name="libraryTable">
Этот файл можно было не включать в коммит.

2018-10-29 05:49 UTC, TimurTechnopolis commented on episode1/src/main/java/edu/technopolis/advjava/demo/CustomString.java
> +        int rounded = (int)Math.ceil(Math.sqrt(length));
Эта стратегия выбора размера кусочка (chunk), на которые разбиваются строки очень спорная. Ну, или напишите комментарий, почему она имеет право на жизнь. Я привёл в пример конкретную задачу - поместить "Войну и мир" в такую строку с возможностью переиспользования. По-моему, стоило сделать конструктор (String source, int chunkSize) с возможностью передачи размера чанка, и перегрузить конструктор (с такую сигнатурой, как у вас), вызывая из него this(source, DEFAULT_CHUNK_SIZE), передав в него какое-то большое значение по умолчанию, к примеру 10 000 символов.

2018-10-29 05:56 UTC, TimurTechnopolis commented on episode1/src/main/java/edu/technopolis/advjava/demo/CustomString.java
> +        int rounded = (int)Math.ceil(Math.sqrt(length));
Вы не совсем верно поняли идею использования строки из кусочков. Смысл в том, что если вы используете большую строку из 1000 кусочков для "Войны и Мира", то для одного тома нжно периспользовать часть строки, а не содавать новые кусочки. А сдургой стороны, нужно использовать только те кусочки, которые нужны для этой подстроки.

2018-10-29 05:57 UTC, TimurTechnopolis requested changes
Пишите больше комментариев и исправьте замечания, пожалуйста.

2018-10-29 05:59 UTC, TimurTechnopolis requested changes
Пишите больше комментариев и исправьте замечания, пожалуйста. 
И самое главное - пулл реквест сделан не в ту ветку. Нужно создать заново.

2018-11-29 20:47 UTC, AlexPentagon reviewed
Простите, не получается залить в свою ветку.
Замечания исправлены.

2019-02-07 10:51 UTC, TimurTechnopolis commented
Изменения в порядке, пуллреквест закрываю, потому что не тот бранч

2019-02-07 10:51 UTC, closed without merging